name: ops-planner-notify

description: Action to notify Ops Planner

author: Denis Iskandarov

inputs:
  project:
    description: Target project in Ops Planner to update
    required: false
  imageTag:
    description: Docker image tag. E.g "GITHUB_SHA"
    required: false
    default: ${{ github.sha }}
  branch:
    description: Commit branch
    required: false
  author:
    description: Commit author's email
    required: true
  url:
    description: Ops Planner API URL
    required: true
  key:
    description: Ops Planner API auth key
    required: true

outputs:
  ops-planner-response:
    description: "Response from Ops Planner API"
    value: ${{ steps.exec-notify.outputs.response }}

runs:
  using: composite
  steps:

  - id: prep-notify
    run: |
      echo "defaultBranch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    shell: bash

  - id: exec-notify
    run: |
      data='{
        "project": "${{ inputs.project || github.event.repository.name }}",
        "author": "${{ inputs.author }}",
        "branch": "${{ inputs.branch || steps.prep-notify.outputs.defaultBranch}}",
        "imageTag": "${{ inputs.imageTag }}",
        "accessKey": "${{ inputs.key }}"
      }'

      response=$(curl -s -w '\n%{http_code}' -H 'Content-Type: application/json' -d "${data}" "${{ inputs.url }}")

      echo "response=$(tail -1 <<< $response)" >> $GITHUB_OUTPUT

      echo $response
      [[ "$(tail -1 <<< $response)" == "200" ]]

    shell: bash
